DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/DetectionsEvaluator.cpp, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/DetectionsEvaluator.h, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/MassInferencer.cpp, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/MassInferencer.h, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/StatsWriter.cpp, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/StatsWriter.h, DeepLearningSuite/DeepLearningSuiteLib/python_modules/tensorflow_detect.py, DeepLearningSuite/Tools/AutoEvaluator/autoEvaluator.cpp
=> Write Time in Auto Evalutor CSV files

README.md
=> Solves #126

docs/README.md
on https://jderobot.github.io/DetectionSuite
=> Initial approach to documentation in GitHub pages

DeepLearningSuite/DeepLearningSuiteLib/DatasetConverters/readers/DatasetReader.cpp, DeepLearningSuite/Tools/Splitter/splitter.cpp
=> Splitter CLI tool restored

DeepLearningSuite/Deps/ros/CMakeLists.txt, DeepLearningSuite/detection_suite/CMakeLists.txt
=> Support for ros melodic added

docs/_pages/funcionality/viewer.md, docs/_pages/resources/class_names.md, docs/_pages/resources/frameworks.md, docs/_pages/resources/tutorial.md
=> COCO class names link changed to right one

DeepLearningSuite/DatasetEvaluationApp/SamplerGeneratorHandler/Evaluator.cpp, DeepLearningSuite/DeepLearningSuiteLib/python_modules/keras_detect.py, DeepLearningSuite/DeepLearningSuiteLib/python_modules/tensorflow_detect.py, DeepLearningSuite/Tools/Evaluator/evaluator.cpp, datasetGenerator/generator.py, datasetGenerator/loadImage.py, sampleGenerator/simpleSampleGenerator/main.py, sampleGenerator/simpleSampleGenerator/sampleGenerator/sample.py
New filename is evaluation_results.csv
Solves #177
=> Evaluation result name changed

docs/_data/navigation.yml, docs/_pages/resources/talks.md
Talk link added and page for talks created
Solves #181.
=> Talks page created and slides added

DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/CMakeLists.txt, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/GenericInferencer.cpp, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/GenericInferencer.h, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/KerasInferencer.cpp, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/KerasInferencer.h, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/PyTorchInferencer.cpp, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/PyTorchInferencer.h, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/TensorFlowInferencer.cpp, DeepLearningSuite/DeepLearningSuiteLib/FrameworkEvaluator/TensorFlowInferencer.h, DeepLearningSuite/DeepLearningSuiteLib/python_modules/pytorch_detect.py, DeepLearningSuite/DeepLearningSuiteLib/python_modules/tensorflow_detect.py, README.md, docs/_pages/funcionality/deployer.md, docs/_pages/installation.md, docs/_pages/resources/frameworks.md, docs/_pages/resources/tutorial.md
Now it is possible to use pytorch as inferencing system.
Still to complete:
fix #189
=> Integrate pytorch inferencing

DetectionStudio/DetectionStudioLib/python_modules/pytorch_detect.py
=> Better types checking 

DetectionStudio/DatasetEvaluationApp/SamplerGeneratorHandler/Detector.cpp, DetectionStudio/DatasetEvaluationApp/gui/ListViewConfig.cpp, DetectionStudio/DetectionStudioLib/Common/Sample.cpp, DetectionStudio/DetectionStudioLib/Common/Sample.h, DetectionStudio/DetectionStudioLib/DatasetConverters/CMakeLists.txt, DetectionStudio/DetectionStudioLib/DatasetConverters/ClassTypeGeneric.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/ClassTypeGeneric.h, DetectionStudio/DetectionStudioLib/DatasetConverters/ClassTypeMapper.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/Tree.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/readers/COCODatasetReader.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/readers/GenericDatasetReader.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/readers/GenericDatasetReader.h, DetectionStudio/DetectionStudioLib/DatasetConverters/readers/ImageNetDatasetReader.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/readers/OpenImagesDatasetReader.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/readers/OpenImagesDatasetReader.h, DetectionStudio/DetectionStudioLib/DatasetConverters/readers/PascalVOCDatasetReader.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/readers/SpinelloDatasetReader.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/readers/YoloDatasetReader.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/writers/GenericDatasetWriter.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/writers/GenericDatasetWriter.h, DetectionStudio/DetectionStudioLib/DatasetConverters/writers/OpenImagesDatasetWriter.cpp, DetectionStudio/DetectionStudioLib/DatasetConverters/writers/OpenImagesDatasetWriter.h, DetectionStudio/DetectionStudioLib/FrameworkEvaluator/DetectionsEvaluator.cpp, DetectionStudio/DetectionStudioLib/FrameworkEvaluator/MassInferencer.cpp, DetectionStudio/DetectionStudioLib/FrameworkEvaluator/TensorFlowInferencer.cpp, samples/names/class-descriptions-boxable.csv
=> Upgrade datasets support for Open Images dataset

DetectionStudio/Dockerfile/Dockerfile, DetectionStudio/Dockerfile/appConfig.yml, README.md
=> Upload complete Dockerfile and image to DockerHub

README.md, docs/_data/navigation.yml, docs/_pages/home.md, docs/_pages/installation.md, docs/_pages/resources/class_names.md, docs/_pages/resources/datasets.md
=> Documentation updated

DetectionStudio/DatasetEvaluationApp/mainwindow.cpp, docs/_pages/installation.md
Couple of comments in installation manual and code modifications to make it work in my ubuntu 20.04
=> solve issue 208

.github/workflows/main.yml, README.md, docs/_pages/installation.md
=> Renamed Detection Studio to Detection Metrics in Dockerhub

docs/_pages/installation.md
=> Updated installation instructions

README.md
Added a how to contribute section of the tutorial followed.
=> Fixes #252- Add a How to Contribute Section

detectionmetrics/cli/evaluate.py, detectionmetrics/datasets/__init__.py, detectionmetrics/datasets/wildscenes.py, docs/_pages/v2/usage.md, examples/wildscenes_image.py
=> Add WildScenes

detectionmetrics/models/torch.py, detectionmetrics/models/torch_model_utils/__init__.py, detectionmetrics/models/torch_model_utils/o3d_kpconv.py, detectionmetrics/models/torch_model_utils/o3d_randlanet.py, detectionmetrics/utils/conversion.py, docs/py_docs/conf.py, tests/test_conversion.py
I have fixed two issues in the existing code.
1. In the function [hex_to_rgb](https://github.com/JdeRobot/DetectionMetrics/blob/ef8942f3a229d3a553c7d14dfb2009537fbcf148/detectionmetrics/utils/conversion.py#L8) I have added the code to handle invalid hex codes ( Wrong length and invalid characters )
2. In the function [get_ontology_conversion_lut](https://github.com/JdeRobot/DetectionMetrics/blob/ef8942f3a229d3a553c7d14dfb2009537fbcf148/detectionmetrics/utils/conversion.py#L51C5-L51C32) I have added the code to implement ignores_classes when ontology_translation is provided too.
I have also added test cases for [conversion.py](https://github.com/JdeRobot/DetectionMetrics/blob/master/detectionmetrics/utils/conversion.py#L51C5-L51C32)
=> Added tests for conversion.py.

tests/test_metrics.py
-   Added  tests for Metrics.py covering:
-   Confusion matrix updates
-   TP, FP, FN, TN calculations
-   Precision, recall, F1-score
-    Accuracy validation (fixed expected values)
-    Edge cases (division by zero, empty inputs)
-  Ensured all tests pass successfully.
=> Added  tests for Metrics Module 

tests/test_io.py, tests/test_lidar.py
This PR consist of the remaining tests some of which some are build previously by contributor now I had completed the all files in utils folder namely io.py and lidar.py using pytest this PR most likely will close the Issue no.#239.
Always available for changes.
=> Build:  complete test for remaining utils files name: io.py and lidar.py (#239)
